Changed validateApiKeyPrefix() to not be private
Changed from:
private void validateApiKeyPrefix()
back to:
void validateApiKeyPrefix()
because of error while building (compileJava was interrupted because of ProjectSettingsConfigurable.java. Description:
"ProjectSettingsConfigurable.java:86: error: validateApiKeyPrefix() has private access in ProjectSettingsComponent
settingsComponent.validateApiKeyPrefix();").